${# Auto-generated by EvoSuite Template Test Generator}
${# Target class: ${classInfo.className}}
${# Generated at: ${generationTime}}
package ${testPackage};

${foreach import in imports}
import ${import};
${end}

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Test class for ${classInfo.simpleName}.
 * Generated from template configuration.
 */
public class ${classInfo.simpleName}Test {

${foreach testCase in testCases}
    /**
     * ${testCase.description}
     */
${if testCase.expectedException != null}
    @Test(expected = ${testCase.expectedException}.class)
${else}
    @Test
${end}
    public void ${testCase.testName}() throws Exception {
        // Arrange — Mock dependencies
${foreach mock in testCase.mocks}
        ${mock.mockCreation};
${if mock.hasStubs}
${foreach stub in mock.stubs}
${if stub.throwsException}
        doThrow(new ${stub.throwException}()).when(${mock.mockVariable}).${stub.method}(${stub.matchers});
${else}
${if stub.hasReturns}
        doReturn(${stub.returns}).when(${mock.mockVariable}).${stub.method}(${stub.matchers});
${else}
        doNothing().when(${mock.mockVariable}).${stub.method}(${stub.matchers});
${end}
${end}
${end}
${end}
${if mock.injectMode == "setter"}
        ${mock.setterMethod}(${mock.mockVariable});
${end}
${end}

        // Arrange — Create SUT and call methods
${foreach call in testCase.methodCalls}
${if call.constructorFor != null}
        ${call.constructorFor} ${call.resultVariable} = new ${call.constructorFor}(${foreach param in call.parameters}${param.paramLiteral}${if !param_isLast}, ${end}${end});
${else}
${if call.resultVariable != null}
${if call.targetVariable != null}
        ${call.returnType} ${call.resultVariable} = ${call.targetVariable}.${call.methodName}(${foreach param in call.parameters}${param.paramLiteral}${if !param_isLast}, ${end}${end});
${else}
        ${call.returnType} ${call.resultVariable} = ${call.methodName}(${foreach param in call.parameters}${param.paramLiteral}${if !param_isLast}, ${end}${end});
${end}
${else}
${if call.targetVariable != null}
        ${call.targetVariable}.${call.methodName}(${foreach param in call.parameters}${param.paramLiteral}${if !param_isLast}, ${end}${end});
${else}
        ${call.methodName}(${foreach param in call.parameters}${param.paramLiteral}${if !param_isLast}, ${end}${end});
${end}
${end}
${end}
${end}

        // Assert
${foreach assertion in testCase.assertions}
        ${assertion};
${end}
    }

${end}
}